runtime: python37
entrypoint: gunicorn -b :$PORT -w 1 weather_flask:app -t 600
instance_class: F2
automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0
  min_idle_instances: 0
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
